Add support for BrowserKit driver
FriendsOfBehat/MinkExtension pull request #14
Opened 2022-01-05 14:00 UTC by thePanz

2022-01-07 11:27 UTC, Tobion commented on spec/Behat/MinkExtension/ServiceContainer/Driver/BrowserKitFactorySpec.php
> +        $this->shouldHaveType('Behat\MinkExtension\ServiceContainer\Driver\DriverFactory');
`::class` can be used

2022-01-07 11:27 UTC, Tobion commented on src/Behat/MinkExtension/ServiceContainer/Driver/BrowserKitFactory.php
> +    private const BROWSERKIT_HTTP_BROWSER_CLASS_NAME =  'Symfony\Component\BrowserKit\HttpBrowser';
`::class` can be used and then there is no need for the constants

2022-01-12 15:08 UTC, Tobion commented on src/Behat/MinkExtension/ServiceContainer/Driver/BrowserKitFactory.php
> +            ->scalarNode('class')->cannotBeEmpty()->end()
does not seem to be used

2022-01-12 15:12 UTC, Tobion commented on src/Behat/MinkExtension/ServiceContainer/Driver/BrowserKitFactory.php
> +                'Install BrowserKit in order to use browserkit driver.'
You need mink-browserkit-driver package not just BrowserKit.

2022-01-12 15:13 UTC, Tobion commented on src/Behat/MinkExtension/ServiceContainer/Driver/BrowserKitFactory.php
> +                sprintf('No implementation of class %s found.', HttpBrowser::class)
the exception message does not fit with what is being tested here

2022-01-13 14:06 UTC, stof commented on src/Behat/MinkExtension/ServiceContainer/Driver/BrowserKitFactory.php
> +        if (class_exists(HttpBrowser::class)) {
you should also check for `HttpClient::class` and `AbstractPart::class`. HttpBrowser cannot be used without the http-client component. And it cannot be used for POST requests without the mime component.

2022-01-13 14:06 UTC, stof commented on src/Behat/MinkExtension/ServiceContainer/Driver/BrowserKitFactory.php
> +        return 'browserkit';
I suggest naming it `browserkit_http` here, as the SymfonyExtension also registers a driver factory using the BrowserKitDriver, but using the KernelBrowser. This would make it clear that this uses browserkit with actual http calls.

What do you think ?

2022-01-13 14:59 UTC, Tobion commented on src/Behat/MinkExtension/ServiceContainer/Driver/BrowserKitFactory.php
> +        return 'browserkit';
Yeah I agree

2022-01-18 15:59 UTC, thePanz commented on src/Behat/MinkExtension/ServiceContainer/Driver/BrowserKitFactory.php
> +        if (class_exists(HttpBrowser::class)) {
I restructured the class existence checks. While I agree on checking the `HttpBrowser::class` and `HttpClient::class` as they are required.

The `AbstractPart::class` is required only for POST requests, as you noted. An exception will be thrown from the HttpBrowser, as:
```php
        if (!class_exists(AbstractPart::class)) {
            throw new \LogicException('You cannot pass non-empty bodies as the Mime component is not installed. Try running "composer require symfony/mime".');
        }```

I find the exception message clear and it also guides the user on how to solve the issue. I would propose to not hard-require the `symfony/mime` here. WDYT?

2022-01-18 16:02 UTC, stof commented on src/Behat/MinkExtension/ServiceContainer/Driver/BrowserKitFactory.php
> +        if (class_exists(HttpBrowser::class)) {
fine with me

2022-01-18 16:19 UTC, stof requested changes

2022-01-18 16:19 UTC, stof commented on src/Behat/MinkExtension/ServiceContainer/Driver/BrowserKitFactory.php
> +            throw new \RuntimeException(sprintf('Class %s not found, did you install symfony/browser-kit?', HttpBrowser::class));
here, I would mention `did you install symfony/browser-kit 4.4+` or remove the check entirely, because `symfony/browser-kit` itself will always be installed at that point (as it is a dependency of `behat/mink-browserkit-driver`, that is checks above)

2022-01-18 16:19 UTC, stof commented on src/Behat/MinkExtension/ServiceContainer/Driver/BrowserKitFactory.php
> +            throw new \RuntimeException('Install BrowserKit Driver in order to use the browserkit_http driver.');
I would say `Install behat/mink-browserkit-driver ...`, mentioning the exact package name, as done in other errors.

2022-03-03 17:05 UTC, kasn commented
Any news on this PR and can I help in any way to get this merged?

2022-03-04 14:18 UTC, thePanz commented on src/Behat/MinkExtension/ServiceContainer/Driver/BrowserKitFactory.php
> +            throw new \RuntimeException(sprintf('Class %s not found, did you install symfony/browser-kit?', HttpBrowser::class));
I would leave the check here, and adapt the exception message as you suggested.
"It should not happen", but better have an additional check here IMHO

2022-03-04 14:22 UTC, thePanz commented
@kasn I addressed the comments from @stof
Not sure who can merge this, maybe @pamil or Yozhef?

2022-04-06 20:55 UTC, mpdude commented
D'oh! Just wrote [almost exactly the same code](https://github.com/FriendsOfBehat/MinkExtension/compare/master...mpdude:browserkit-driver?expand=1) before I found this.

Thank you @thePanz!

@pamil, @lchrusciel or @Zales0123, who of you has enough karma to decide how to proceed?

2022-04-12 09:09 UTC, mageekguy commented
Nobody here to commit this PR? Be able to use BrowserKit instead of Goutte seems to me very important for this project, mostly because it is currently impossible to setup a goutte driver due to incompatibility introduced by BrowserKit.

2022-04-28 15:45 UTC, mpdude commented
@Yozhef you did the last merge in this repo here... what do you think?

2022-05-10 12:22 UTC, mvanduijker commented
Is there any help needed to get this merged?

2022-05-23 13:34 UTC, acsauk commented
Also hoping this is merged soon so I can stop relying on a fork I've made to apply the changes. 

@pamil @lchrusciel @Zales0123 - I'm not sure how involved you are with this repo but as you're listed as the 3 members of `FriendsOfBehat` is this something you could merge?

2022-07-01 05:54 UTC, mpdude commented
@pamil @lchrusciel @Zales0123 could you please leave a short comment here?

If you don’t want to merge or maintain this repo at all, that’s fine. It would be helpful already if we know what to expect. 🙏🏻

2022-07-01 06:58 UTC, Yozhef commented
@mpdude @thePanz @acsauk  looks good but please upgrade to master to run ci process

2022-07-01 07:56 UTC, merged

2022-07-01 07:59 UTC, Yozhef commented
sorry for such a long answer, I was unable to work due to the war in my country

2022-07-01 08:17 UTC, thePanz commented
Thank you @Yozhef  :yellow_square: :blue_square:

2022-07-01 20:22 UTC, mpdude commented
Oh my… I am so sorry. I really hope you and your loved ones are safe. Stay strong 💪🏻 

💙💛 from 🇩🇪

2023-06-29 14:09 UTC, baschny commented
Very cool that I found this, I was also thinking about forking original mink-extension and adding it on my own, then I found this. The PR could have added this also to the documentation, as the README does not mention it and is now misleading ("No updates other than Symfony compatibility will be provided"), so I quickly turned my back to it.

2023-06-29 14:37 UTC, stof commented
the readme has indeed not been updated when changing the scope of the project.

2023-06-29 14:43 UTC, baschny commented
Just as a note to the afterworld, to activate the browserkit driver with this forked MinkExtension, one needs to:

1. require `symfony/http-client`
2. add this to your `behat.yml`:
```
  extensions:
    Behat\MinkExtension:
      ...
      browserkit_http: ~
      ...
 ```