Implement WebdriverClassicDriver factory
FriendsOfBehat/MinkExtension pull request #26
Opened 2024-03-04 19:31 UTC by uuf6429

2024-03-05 09:59 UTC, aik099 requested changes

2024-03-05 09:59 UTC, aik099 commented on spec/Behat/MinkExtension/ServiceContainer/Driver/WebdriverClassicFactorySpec.php
> +    public function it_is_named_zombie(): void
The method name looks like a copy/paste error.

2024-03-05 09:59 UTC, aik099 commented on src/Behat/MinkExtension/ServiceContainer/Driver/WebdriverClassicFactory.php
> +class WebdriverClassicFactory implements DriverFactory
I recommend using 
https://github.com/FriendsOfBehat/MinkExtension/blob/master/src/Behat/MinkExtension/ServiceContainer/Driver/Selenium2Factory.php (with proper adjustments) as a source of inspiration, when creating this driver, because they have a lot in common.

2024-03-05 10:21 UTC, uuf6429 commented on spec/Behat/MinkExtension/ServiceContainer/Driver/WebdriverClassicFactorySpec.php
> +    public function it_is_named_zombie(): void
oops, agreed

2024-03-05 10:27 UTC, uuf6429 commented on src/Behat/MinkExtension/ServiceContainer/Driver/WebdriverClassicFactory.php
> +class WebdriverClassicFactory implements DriverFactory
I started with that and ended up removing a lot of unnecessary things:
1. requiring a specific capabilities configuration structure has caused confusion and incompatibilities in the past, I would rather leave it to the end user to set that up correctly
2. why have chrome/firefox-specific configuration schema
3. the tags stuff seems highly opinionated (why travis and jenkins but not github or gitlab?) and functionally unnecessary

What is actually missing that you'd rather have back?

2024-03-05 12:36 UTC, aik099 commented on src/Behat/MinkExtension/ServiceContainer/Driver/WebdriverClassicFactory.php
> +class WebdriverClassicFactory implements DriverFactory
> 1. requiring a specific capabilities configuration structure has caused confusion and incompatibilities in the past, I would rather leave it to the end user to set that up correctly

If the current implementation allows defining the free-form capabilities (including the `goog:chromeOptions` and `moz:firefoxOptions` sub-arrays, then I'm ok with that.

> 2. why have chrome/firefox-specific configuration schema

I have no idea. I use Mink, not Behat.

> 3. the tags stuff seems highly opinionated (why travis and jenkins but not github or gitlab?) and functionally unnecessary (if setting tags is important, we should have some mechanism in this repo to generate tags instead of copy&pasting the same code all over the place)

I know, that the `tunnel-identifier` and `build` capabilities allow test grouping in the BrowserStack/SauceLabs and such. Adding support for this would simplify migration for users, that use `selenium2` currently, but want to upgrade.

If you don't see GitHub Actions/GitLab CI support in the driver factories, then it wasn't requested by anyone. No need to worry upfront.

> What is actually missing that you'd rather have back?

It seems, that only the code, that defines these capabilities based on the environment variables:
* 'tunnel-identifier'
* 'build'
* 'tags'
.

2024-03-05 13:05 UTC, uuf6429 commented on src/Behat/MinkExtension/ServiceContainer/Driver/WebdriverClassicFactory.php
> +class WebdriverClassicFactory implements DriverFactory
> It seems, that only the code, that defines these capabilities based on the environment variables:

ok, I'll look into those later 👍

2024-04-05 18:38 UTC, uuf6429 commented on src/Behat/MinkExtension/ServiceContainer/Driver/WebdriverClassicFactory.php
> +class WebdriverClassicFactory implements DriverFactory
done

2024-04-05 18:45 UTC, uuf6429 reviewed
@stof a couple of points:
1. homepage link in composer.json is broken.
2. the original documentation is now archived; that means it won't be updated, correct?
3. that also relates to the point here: https://github.com/minkphp/webdriver-classic-driver/pull/19/files#r1536878118

2024-04-06 09:27 UTC, stof commented on composer.json
> +        "php": "^7.4 || ^8",
this does not belong to this PR IMO. It is unrelated to adding the new factory.

2024-04-06 09:27 UTC, stof commented on src/Behat/MinkExtension/ServiceContainer/Driver/EnvironmentCapabilities.php
> +trait EnvironmentCapabilities
Please tag it as `@internal`

2024-04-06 09:27 UTC, stof commented on composer.json
> +        "mink/webdriver-classic-driver": "dev-main"
is this actually necessary ?

2024-04-06 11:51 UTC, uuf6429 commented on composer.json
> +        "php": "^7.4 || ^8",
Agreed, but it won't be changed otherwise; and since it's not breaking or changing anything functional, I don't see any harm in that.

2024-04-06 11:57 UTC, uuf6429 commented on composer.json
> +        "mink/webdriver-classic-driver": "dev-main"
Well for dev, it's useful. In fact, that was how I found out the [driver's namespace was wrong](https://github.com/minkphp/webdriver-classic-driver/pull/20).
By the way, we're doing the same thing for `behat/mink-goutte-driver`.

On a related note, some driver factories are referencing non-existent classes without mentioning their source, for example [`Selenium4Factory` references `Selenium4Driver`](https://github.com/uuf6429/MinkExtension/blob/aad1c3f58450c6d867fc9cf295a41d6de9b4421a/src/Behat/MinkExtension/ServiceContainer/Driver/Selenium4Factory.php#L58-L58) without [the providing package](https://packagist.org/?query=MinkSelenium4Driver).

2024-04-06 12:00 UTC, uuf6429 commented on composer.json
> +        "php": "^7.4 || ^8",
(but I can roll it back if you have a strong opinion against it)

2024-04-06 12:01 UTC, stof commented on composer.json
> +        "mink/webdriver-classic-driver": "dev-main"
Given that there is no official Selenium4Driver, I don't think this factory should even exist in this extension. third-part drivers should have a separate Behat extension using the extension point to register third-part factories (similar to how SymfonyExtension registers a factory for a driver using BrowserKitDriver with the KernelBrowser calling the Symfony kernel directly, which obviously cannot have its factory in MinkExtension itself as it would not work without the SymfonyExtension)

2024-04-06 12:03 UTC, stof commented on composer.json
> +        "php": "^7.4 || ^8",
I suggest submitting that as a separate PR, so that it has its dedicated entry in the git history of the repo (note that I can merge this separate PR).

2024-04-06 12:10 UTC, uuf6429 commented on composer.json
> +        "mink/webdriver-classic-driver": "dev-main"
OK, but that's kinda my point. Referencing a non-existent class in some unknown/non-existent package is the worst case; you think it's a 3rd party package and I thought it was an official package that somehow vanished.

Solution: all the referenced classes must/should be available during dev.

2024-04-06 12:22 UTC, stof commented on composer.json
> +        "mink/webdriver-classic-driver": "dev-main"
also, 3rd party drivers should have their own PHP namespace (which is not the case in this case)

2024-04-07 12:27 UTC, uuf6429 commented on composer.json
> +        "mink/webdriver-classic-driver": "dev-main"
@stof so back on topic, this change makes sense, right? Can I resolve this comment?

2024-04-07 12:29 UTC, uuf6429 commented on composer.json
> +        "php": "^7.4 || ^8",
done here: https://github.com/FriendsOfBehat/MinkExtension/pull/28

2024-04-08 07:35 UTC, aik099 approved these changes
Approving, because all points from my previous review were addressed.

2024-04-12 08:05 UTC, benr77 commented
If I use `webdriver-classic:` in `behat.yml` then I get the following error:

```
Unrecognized option "webdriver_classic" under "testwork.mink.sessions.default". Did you mean "webdriver-classic"?
```

But this is reporting that I do what I have done. It looks like somewhere the hyphen is being replaced by an underscore.

Solution is to change the hyphen to an underscore [here](https://github.com/uuf6429/MinkExtension/blob/18a3f770db963f38b7d73d7061b9ffd0e0cda457/src/Behat/MinkExtension/ServiceContainer/Driver/WebdriverClassicFactory.php#L18)

2024-04-12 19:10 UTC, aik099 commented
@benr77 , I'm new to Behat. Please describe the steps needed to create a test project with Behat + MinkExtension + this PR code so that it's easier to diagnose the problem. Yaml itself doesn't prohibit hyphen usage inside the key names.

2024-04-12 21:12 UTC, uuf6429 commented
@benr77 @aik099 The other drivers are using underscores instead of dashes. It probably makes sense to do it that way, if anything just to keep it consistent.

As to the buggy behaviour, I don't feel like investigating another thing that will take ages to be accepted. 🤷

2024-04-13 09:04 UTC, benr77 commented
This underscore fix is now working as expected. Thank you. Hopefully this PR can get merged soon.

2024-04-13 17:06 UTC, aik099 commented
FYI: The `webdriver-classic` in YAML becoming `webdriver_classic` in PHP is part of the normalization process done by the used Symfony/Config Component: https://symfony.com/doc/current/components/config/definition.html#normalization

> The separator used in keys is typically _ in YAML and - in XML. For example, auto_connect in YAML and auto-connect in XML. The normalization would make both of these auto_connect.

2024-06-26 11:58 UTC, claudiu-cristea commented
Landed here trying to use [minkphp/webdriver-classic-driver](https://github.com/minkphp/webdriver-classic-driver) with my Behat setup. @benr77, could you share a `behat.yml` that uses this PR+[minkphp/webdriver-classic-driver](https://github.com/minkphp/webdriver-classic-driver)?

2024-06-26 12:12 UTC, benr77 commented
@claudiu-cristea All I have is this behat.yaml, alongside using this branch instead of main - the important bit is using `webdriver_classic`.

```yaml
default:
  suites:
    default:
      contexts:
        - FeatureContext
  extensions:
    Behat\MinkExtension:
      base_url: http://php
      browser_name: chrome
      sessions:
        default:
          webdriver_classic:
            browser: chrome
            wd_host: http://chrome:4444/wd/hub
            capabilities:
              browserName: chrome
              platform: any
              chrome:
                switches:
                  - '--headless'
                  - '--window-size=1200,1100'
                  - '--disable-gpu'
                  - '--no-sandbox'
```

2024-08-06 14:35 UTC, vever001 commented on src/Behat/MinkExtension/ServiceContainer/Driver/Selenium4Factory.php
> +            ),
Hello,

Shoudln't this be: `array_merge($this->guessEnvironmentCapabilities(), $config['capabilities']),` ?
Right now capabilities don't seem to be passed correctly to WebdriverClassicDriver::__construct and are nested in an extra 'capabilities' array, therefore ignored.

2024-08-06 16:15 UTC, uuf6429 commented on src/Behat/MinkExtension/ServiceContainer/Driver/Selenium4Factory.php
> +            ),
Agreed, I only noticed this recently. 😅

2024-08-06 16:23 UTC, uuf6429 commented on src/Behat/MinkExtension/ServiceContainer/Driver/Selenium4Factory.php
> +            ),
Fixed.

2024-08-06 16:31 UTC, aik099 commented on src/Behat/MinkExtension/ServiceContainer/Driver/Selenium4Factory.php
> +            ),
@uuf6429 , have you pushed the changes? I see the same code, that @vever001 commented on.

2024-08-06 16:33 UTC, aik099 commented on src/Behat/MinkExtension/ServiceContainer/Driver/Selenium4Factory.php
> +            ),
I see, that you've changed `WebdriverClassicFactory.php` file (which is also good), but the issue was with `Selenium4Factory.php` file.

2024-08-06 17:26 UTC, uuf6429 commented on src/Behat/MinkExtension/ServiceContainer/Driver/Selenium4Factory.php
> +            ),
> @uuf6429 , have you pushed the changes? I see the same code, that @vever001 commented on.
> 
> I see, that you've changed `WebdriverClassicFactory.php` file (which is also good), but the issue was with `Selenium4Factory.php` file and maybe other factory files.

Hmm, I missed that one.

On a related note, shouldn't we have tests to avoid this sort of situation?

2024-08-06 17:37 UTC, stof commented on composer.json
> +        "mink/webdriver-classic-driver": "dev-main"
I suggest using `^1.0@dev`, relying on the branch alias of the main branch instead of requiring it directly (which would then allow using stable versions easily once they exist)

2024-10-03 16:16 UTC, stof approved these changes

2024-10-03 16:16 UTC, merged

2025-12-20 07:41 UTC, mpdude commented
@uuf6429  do you think you could create a PR to add this feature to the documentation?

2025-12-20 08:07 UTC, uuf6429 commented
@mpdude To be honest, it doesn't seem worth the time updating documentation that is not visible. Neither this repo nor the original (archived) one point to the documentation (which I only guessed you're pointing at, by seeing your last commit in the repo). Also refer to issue #30.

2025-12-21 15:48 UTC, aik099 commented on composer.json
> +        "mink/webdriver-classic-driver": "^1.0@dev"
@uuf6429, are you sure that this line is needed?

2025-12-21 16:59 UTC, uuf6429 commented on composer.json
> +        "mink/webdriver-classic-driver": "^1.0@dev"
Yes, otherwise it results in missing references in classes like `WebdriverClassicFactory.php`.

Note that it's in require-dev so it doesn't impact users - it's specifically for contributors (and tests or static code analyses) of this repo.

Why do you ask?

2025-12-21 17:08 UTC, aik099 commented
I'm wondering why other driver factory tests don't require any `require-dev` dependencies to run, but this one does.

P.S.
Dependency to Goutte driver is replaced with browserkit driver in another PR.

2025-12-21 17:26 UTC, uuf6429 commented on composer.json
> +        "mink/webdriver-classic-driver": "^1.0@dev"
> I'm wondering why other driver factory tests don't require any require-dev dependencies to run, but this one does.

It's one of 3 cases:
1. shoddy/half-baked design, such as `Selenium4Factory` - it expects a specific class to exist, otherwise fails with "Install MinkSelenium4Driver in order to use %s driver" (and no real indication of a composer package that would work)
2. it's a variation or builds on top of an existing driver and just sets some defaults, such as `AppiumFactory`
3. or it actually does, such as `GoutteFactory` (`behat/mink-goutte-driver`)


I think it should be obvious that all classes referenced anywhere in the code, should actually exist during development, right?

In the ideal world:
- such dependencies should be available at development time
- they should be added as (composer) suggestions in this repo

> Dependency to Goutte driver is replaced with browserkit driver in another PR.

ok, but that doesn't really matter in this discussion.

2025-12-21 18:33 UTC, aik099 commented on composer.json
> +        "mink/webdriver-classic-driver": "^1.0@dev"
Thank you for the explanation. Then we'll keep it as-is.