Fix deprecated use of ReflectionParameter::getClass for php 8
FriendsOfBehat/MinkExtension pull request #9
Opened 2021-05-05 17:08 UTC by cacahouwete

2021-05-06 09:00 UTC, cacahouwete commented
@pamil is it possible to review this PR ?

2021-05-18 18:50 UTC, stronk7 commented
FYI, we have applied the patch here to our (hopefully temporal) fork and it's working ok, so far. No more PHP Deprecated warnings.

Only point that called my attention are the changes back-slashing global scope functions (`\class_exists()...) that doesn't seem to be the rule followed by other parts of MinkExtension... just saying.

2021-05-19 23:24 UTC, andrewnicols requested changes
These changes look good to me except for the use of \ to globally scope functions which are in the global scope.

2021-05-19 23:24 UTC, andrewnicols commented on src/Behat/MinkExtension/ServiceContainer/Driver/GoutteFactory.php
> +        if (!\class_exists('Behat\Mink\Driver\GoutteDriver')) {
No need to prefix these with \ They are already globally scoped.

2021-05-19 23:24 UTC, andrewnicols commented on src/Behat/MinkExtension/ServiceContainer/Driver/GoutteFactory.php
> +        return \interface_exists('GuzzleHttp\ClientInterface') &&
No need to prefix these with \ They are already globally scoped.

2021-05-21 08:53 UTC, cacahouwete commented on src/Behat/MinkExtension/ServiceContainer/Driver/GoutteFactory.php
> +        return \interface_exists('GuzzleHttp\ClientInterface') &&
Done

2021-05-21 08:53 UTC, cacahouwete commented on src/Behat/MinkExtension/ServiceContainer/Driver/GoutteFactory.php
> +        if (!\class_exists('Behat\Mink\Driver\GoutteDriver')) {
Done

2021-06-18 08:59 UTC, cacahouwete commented
@andrewnicols is it possible to merge it ?

2021-06-21 03:33 UTC, andrewnicols commented
@cacahouwete , nothing to do with me. This repository is the responsibility of FriendsOfBehat I just gave a review as we have included this pull request in our packages.

Pinging @lchrusciel , @pamil , and @Zales0123 - this issues blocks support for PHP 8.0 and is therefore critical for most.

2021-12-07 10:02 UTC, acsauk commented
Hey @pamil - is there a likelihood of this being merged soon? It's causing some failures in our behat suites following a PHP 8 upgrade. If it's not on the cards are you able to suggest any alternative approaches to the package? Thanks.

2021-12-13 08:48 UTC, Yozhef approved these changes
thanks for the help we will be glad to see you again

2021-12-13 08:48 UTC, merged